"""initial migration

Revision ID: 787fa1f0fb3c
Revises: 
Create Date: 2026-02-28 09:28:12.314281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '787fa1f0fb3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('exp_years', sa.Integer(), nullable=True),
    sa.Column('key_skills', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('employment', sa.String(length=36), nullable=True),
    sa.Column('remote', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_category'), 'candidates', ['category'], unique=False)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('ix_candidates_location'), 'candidates', ['location'], unique=False)
    op.create_index(op.f('ix_candidates_title'), 'candidates', ['title'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('exp_years_min', sa.Integer(), nullable=True),
    sa.Column('exp_years_max', sa.Integer(), nullable=True),
    sa.Column('key_skills', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('employment', sa.String(length=36), nullable=True),
    sa.Column('remote', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_category'), 'vacancies', ['category'], unique=False)
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_index(op.f('ix_vacancies_location'), 'vacancies', ['location'], unique=False)
    op.create_index(op.f('ix_vacancies_status'), 'vacancies', ['status'], unique=False)
    op.create_index(op.f('ix_vacancies_title'), 'vacancies', ['title'], unique=False)
    op.create_table('scoring',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False, comment='ID кандидата'),
    sa.Column('vacancy_id', sa.String(length=36), nullable=False, comment='ID вакансии'),
    sa.Column('match_score', sa.Float(), nullable=False, comment='Оценка соответствия 0-100%'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Уверенность модели в оценке (0-1)'),
    sa.Column('analysis', sa.JSON(), nullable=True, comment='Структурированный разбор: сильные стороны, пробелы, рекомендации'),
    sa.Column('llm_raw_response', sa.Text(), nullable=True, comment='Сырой ответ от LLM (для отладки и аудита)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата расчёта скоринга'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_candidate_id'), 'scoring', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scoring_id'), 'scoring', ['id'], unique=False)
    op.create_index(op.f('ix_scoring_vacancy_id'), 'scoring', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_vacancy_id'), table_name='scoring')
    op.drop_index(op.f('ix_scoring_id'), table_name='scoring')
    op.drop_index(op.f('ix_scoring_candidate_id'), table_name='scoring')
    op.drop_table('scoring')
    op.drop_index(op.f('ix_vacancies_title'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_status'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_location'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_category'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_candidates_title'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_location'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_category'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
